version: 2
jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run: 
          name: Lint
          command: |
            rustup component add clippy
            cargo clippy
      - run: 
          name: Formatted
          command: |
            rustup component add rustfmt-preview
            cargo fmt -- --check
      - run: 
          name: Build
          command: | 
            rustup toolchain install nightly
            cargo build --all --release
      - run: 
          name: Test
          command: cargo test --all --release
